### ISSUE TITLE
Numerical issues relating to Cholesky decomposition

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/GaussianProcesses.jl#1]
The Gaussian Processes fitting sometimes fails due to a PosDef error, especially when observation noise is low. This also leads to the occasional failure of the optimize! function. Error can be avoided by increasing noise parameter of GP, or by fixing noise in the optimize!

An automated way of dealing with this will be required, for instance the Rasmussen package for Matlab automatically adds small amounts of noise to the covariance matrix when the noise parameter is very small.

**Comment by nemethis** [comment]
Added a fixed 1e-8 nugget term to ensure numerical stability. A similar step has also been added to the predict function. Regularisation through eigen decomposition could also be investigated as an alternative solution

**Comment by karajan9** [comment]
I came across this bug during some experimentation:
```
using GaussianProcesses
using Distributions

g(x, y) = 5x - 0.1(x-y)^2 + 0.8x*y - 0.05y^3

n = 15
x = rand(Uniform(-5, 5), n)
y = rand(Uniform(-5, 5), n)
z = g.(x, y)

mZero = MeanZero()
kern = Poly(1.0, 0.0, 3)
gp = GP([x'; y'], z, mZero, kern)
optimize!(gp)
```
```
julia> predict_y(gp, [0.0 0.0]')                                            
ERROR: PosDefException: matrix is not positive definite; Cholesky factorizat
ion failed.
```

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```
with GaussianProcesses v0.9.0.

As @fairbrot mentioned, doing `optimize!(gp, noise = false)` instead seems to solve the problem.
