### ISSUE TITLE
predicting a derivative

### ISSUE THREAD

**Issue by snirgaz** [STOR-i/GaussianProcesses.jl#114]
Is possible to predict the derivative (dy/dx) at some point x of an optimized Gaussian process?

**Comment by maximerischard** [comment]
Currently, predicting the derivative is not a feature we've implemented. We've discussed it in #102, so it's on our list of desirable features, but at the moment none of the regular contributors have the bandwidth to work on this feature. Please get in touch if you would be interested in working on the feature, and I would be happy to help.
