### ISSUE TITLE
Code update

### ISSUE THREAD

**Issue by gugushvili** [STOR-i/GaussianProcesses.jl#115]
I'm trying to reproduce [this example](https://github.com/STOR-i/GaussianProcesses.jl/blob/master/notebooks/Poisson%20regression.ipynb), but get an error. The offending command is `rand(gp, xtest)`, it seems, and the error report is:

```
ERROR: LoadError: MethodError: no method matching unwhiten!(::Array{Float64,2}, ::Array{Float64,2})
```
Would be nice if you update the package and documentation to reflect the latest Julia release (I'm running v1.1). Thanks.

P.S. The [arXiv paper](https://arxiv.org/abs/1812.09064) also contains commands that have been deprecated, like `linspace`.

**Comment by chris-nemeth** [comment]
Thanks for raising this issue. We're in the process of incrementing the version so we'll fix this and correct the paper.

**Comment by chris-nemeth** [comment]
This should now be fixed on the master branch. We'll soon be incrementing the package version as well.

**Comment by gugushvili** [comment]
Thanks, I was able to reproduce the code. Now I am trying to do the same with Section 4.3 of the arXiv paper. However, I can't find the coal.csv dataset in the repository (there is only CO2_data.csv available). Of course, I can also pull it from R, but maybe this is not what all the users would like to do.

**Comment by chris-nemeth** [comment]
I've just pushed the coal.csv to the master branch (same folder as CO2_data.csv).

**Comment by gugushvili** [comment]
After some trial and error, I was able to do that example as well. The code in the arXiv paper requires updating.

P.S. There is a typo in the paper, page 12: "There is an optional var argument which can be used to plot the two-dimensional variance (see Figure 3)". This should refer to Figure 4.

**Comment by chris-nemeth** [comment]
Thanks @gugushvili for spotting the typo on page 12. I'll close this issue now.
