### ISSUE TITLE
identifying parameters from output

### ISSUE THREAD

**Issue by fmeulen** [STOR-i/GaussianProcesses.jl#130]
I may not have carefully looked through the docs, but I can't see a clear description on the ordering of parameters in ```optimize!``` and ```mcmc```. It would be nice if these were returned as names tuples. A similar remark applied to the function get_params (is there a clear reason why this function is not exported?).

**Comment by maximerischard** [comment]
Good question. These parameter vectors are meant to be used internally by the optimisation or inference procedures, and no effort has gone into making them human-readable. This is also why these functions are not exported. To get human-readable parameter values, you would instead inspect the parameters in the kernel, as well as the parameters of the mean function and `logNoise`. But here again the `show` function for kernels is quite basic and could use some love. One thing we've talked about is parameter types that would be more amenable to pretty-printing.

I'll close this now, but feel free to reopen if you want to discuss further or have some ideas for improvements.
