### ISSUE TITLE
predict forces Sigma to have all non-negative elements

### ISSUE THREAD

**Issue by matthewrfellows** [STOR-i/GaussianProcesses.jl#14]
In GP.jl, the "_predict" function computes Sigma, then does Sigma = max(Sigma,0) before returning it.
Unless this isn't the standard element-wise "max" function, this is obviously not what you want, since covariance matrices can have negative off-diagonal elements.

**Comment by nemethis** [comment]
You're absolutely right, thanks for spotting this. We originally added the Sigma=max(Sigma,0) thinking of the default predict function which gives just the diagonal elements. We must have moved it to the wrong place when trying to improve the speed. Sorry about that and thanks again for letting us know.
