### ISSUE TITLE
Implementing the scikit-learn interface

### ISSUE THREAD

**Issue by cstjean** [STOR-i/GaussianProcesses.jl#15]
Hi,

I'm the author of [ScikitLearn.jl](https://github.com/cstjean/ScikitLearn.jl), a port/wrapping of the scikit-learn interface. I'd like to have an example of [implementing the interface](https://github.com/cstjean/ScikitLearnBase.jl) before announcing the package, and GaussianProcesses.jl is a good candidate. Since you're already storing the hyperparameters in `GP`, it will be straight-forward. If you're interested, I will submit a PR.

**Comment by nemethis** [comment]
Thanks for this. Yes, we're interested please submit the PR.

**Comment by nemethis** [comment]
This functionality has now been merged into the master branch. Thanks to cstjean for his pull request.

**Comment by cstjean** [comment]
Thanks to you guys for your support!

I was thinking today about how we could wrap the Optim.jl type-II
optimization into a separate regressor that automatically fits the
hyperparmeters. Maybe in the next iteration!
