### ISSUE TITLE
Missing KernelData for ElasticCovStrat?

### ISSUE THREAD

**Issue by baggepinnen** [STOR-i/GaussianProcesses.jl#155]
I have a GP with 
```julia
debug> gp.covstrat
GaussianProcesses.ElasticCovStrat(1000, 1000)
```
Inside 
```julia
update!(model::GPE{X,Y,M,K,P,D}, x, y)
```
the following `fit!` function is called
```julia
function fit!(gp::GPE{X,Y}, x::X, y::Y) where {X,Y}
    length(y) == size(x,2) || throw(ArgumentError("Input and output observations must have consistent dimensions."))
    gp.x = x
    gp.y = y
    gp.data = KernelData(gp.kernel, x, x, gp.covstrat)
    gp.cK = alloc_cK(gp.covstrat, length(y))
    gp.dim, gp.nobs = size(x)
    initialise_target!(gp)
end
```
which calls `KernelData` and tries to asssign that into `gp.data`. Since there is no `KernelData` method that accepts `ElasticCovStrat`, it hits this method
```julia
KernelData(k::Kernel, X1::AbstractMatrix, X2::AbstractMatrix, covstrat::CovarianceStrategy) = EmptyData()
```
and the returned `EmptyData` cannot be converted to the correct type.

```julia
ERROR: MethodError: Cannot `convert` an object of type 
  GaussianProcesses.StationaryARDData{Array{Float64,3}} to an object of type 
  GaussianProcesses.StationaryARDData{ElasticPDMats.AllElasticArray{Float64,3}}
```

**Comment by jbrea** [comment]
Are you referring to the `update!` function of `BayesianOptimization`? I think [this commit](https://github.com/jbrea/BayesianOptimization.jl/commit/3046840e1086c8c05d3675a3eeb754ca5b699a63) should have fixed the issue... Which versions are you using?

**Comment by baggepinnen** [comment]
It appears that you are right, I must have been screwing up when trying to update my dependencies. Sorry for the noise :(
