### ISSUE TITLE
Question: Are multiple inputs possible?

### ISSUE THREAD

**Issue by elakelaiset** [STOR-i/GaussianProcesses.jl#161]
Hi together,
I am new to GPR and have a question whether this Julia package can handle multiple inputs. With multiple inputs it is meant that the obtained data/ observations, e.g. temperature measurements, are not only dependent on a single variable, like daytime, but on several inputs, like daytime, measurement height. So that in the end one can obtain regressed data for a given daytime and height.

Kind Regards
Sebastian

**Comment by thomaspinder** [comment]
Hi @elakelaiset. Multiple inputs are within the scope of GPs and this package - see the final example of https://github.com/STOR-i/GaussianProcesses.jl/blob/master/notebooks/Regression.ipynb where we have 2 input variables. 

One key point when having more than one input is whether or not your data is isotropic. This assumption will propagate into the kernel function, where an isotropic assumption will lead you to believe the data varies equally in every dimension. Often this is not the case, i.e. temperature varies more latitudinally than longitudinally. If the isotropic assumption is not valid, then you'd be best specifying an ARD kernel, which will assign individual kernel parameters to each dimension.
