### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mohamed82008** [STOR-i/GaussianProcesses.jl#188]
Hi! Thanks for this great package. Can I please get a new release here? I am getting compat issues with the current version.

**Comment by mohamed82008** [comment]
bump

**Comment by chris-nemeth** [comment]
I've merged the PR for the compat update so you can use this on the master branch. I'll release a minor update to the package soon as well.

**Comment by mohamed82008** [comment]
Thanks. I am trying to use Nonconvex.jl with Hyperopt.jl which depends on this package. The wrapping code is implemented in Nonconvex (https://github.com/mohamed82008/Nonconvex.jl#starting-point-optimization-using-hyperoptjl) but I don't want to announce it to users before everything is released.

**Comment by mohamed82008** [comment]
Thanks for the release :)
