### ISSUE TITLE
Sampling from prior or posterior distribution

### ISSUE THREAD

**Issue by ahwillia** [STOR-i/GaussianProcesses.jl#19]
Is it possible to draw random samples from a `GP`? At the very least, sampling from the prior would be very easy to implement. This would be useful for me and others as well, I'd expect. I think the conventional API would be along the lines of:

```julia
gp = GP(x,y,m,k)
rand(gp,10) # draw 10 samples from posterior
```

I'm also interested in sampling from the prior distribution. This is perhaps a separate issue, but I would prefer that there be a separate function `fit!(gp::GP,x::Array,y::Array)` to fit the model. This way I could draw samples from the prior like so:

```julia
gp = GP(m,k)  # create prior
rand(gp,10)   # draw 10 samples from prior
fit!(gp,x,y)   # fit to data
rand(gp,10)   # draw 10 samples from posterior
```

**Edit/Update:** I dug into the code a little bit and found the `full_cov` option, which suggests a wrapper along the lines of:

```julia
using Distributions

function rand(gp::GP, n::Int; x_ax=collect(linspace(0,1)))
    mu,sigma = predict(gp,x_ax;full_cov=true)
    return rand(MvNormal(mu,sigma),n)
end
```

I think this sort of works? I tend to get a `Base.LinAlg.PosDefException` unless I add a small identity matrix to `sigma`. Also, I have been trouble using `gp = GP()` to sample from the prior. Any help on this is greatly appreciated!

**Comment by nemethis** [comment]
Thanks for bringing this up. Sampling from both the prior and posterior is pretty straightforward and something that I've been meaning to add for a while. Your suggestion for sampling from the posterior is probably how we'd go about doing it. 

We agree about the fit! function; in fact we already have such a function as part of our support for the ScikitLearn interface, but hadn't got around to exporting the functionality.

Just give me a day or so to push the changes. Thanks again.

**Comment by nemethis** [comment]
We've fixed the PosDef issue with the covariance matrix and implemented a rand(gp,..) function which samples from the prior and posterior. Have a look at the docs/sample.jl file for an implementation. 

We still have to update the fit! function, but as you'll see from sample.jl you should now be able to do what you need.

**Comment by ahwillia** [comment]
Excellent! Thanks for the quick response.
