### ISSUE TITLE
Wrong gp.cK calculation in GP.jl function update_mll! if noise is used

### ISSUE THREAD

**Issue by zerocewl** [STOR-i/GaussianProcesses.jl#21]
- the calculation of gp.cK in function update_mll! in GP.jl has wrong results if a noise is used
- in line 55 a **2*** should be added for the logNoise

old version
` gp.cK = PDMat(crossKern(gp.x,gp.k) + exp(gp.logNoise)*eye(gp.nobsv) + 1e-8*eye(gp.nobsv))`

new code version
` gp.cK = PDMat(crossKern(gp.x,gp.k) + exp(2*gp.logNoise)*eye(gp.nobsv) + 1e-8*eye(gp.nobsv))`

i checked the results with some testdata from the gpml matlab box, maybe someone can add some logical tests too ;-)

**Comment by nemethis** [comment]
Thanks for spotting this. I'll fix this now and push the change. You're right about the extra tests, this is something which we're working on.

**Comment by maximerischard** [comment]
If `logNoise` is the log of the noise variance, then I don't see where that `2*` is supposed to come from. It implies that we're adding a sigma^4 term to the variance.

**Comment by nemethis** [comment]
This is something that we should clarify in the documentation that we're using logNoise = log(sigma) rather than log(sigma^2). I think we changed to this setting to be consistent with Rasmussen's GPML package. The second term, 1e-8*eye(gp.nobsv) is just for numerical stability in case the optimizer sets logNoise to be too small, but we'll look at how to implement this in a better way.

**Comment by maximerischard** [comment]
OK, that all makes sense then. It's not just the documentation though, there's a few inconsistencies that tripped me up when I was trying to figure this out from the code:
comment on line 26 of GP.jl
```{julia}
logNoise::Float64       # log variance of observation noise
```
lines 32 and 33 of GP.jl
```{julia}
cK::PDMat                 # (k + obsNoise)
alpha::Vector{Float64}  # (k + obsNoise)⁻¹y
```
line 233 of GP.jl
```{julia}
print(io,"\n  Variance of observation noise = $(exp(gp.logNoise))")
```

**Comment by nemethis** [comment]
I already fixed the 1st and 3rd point but missed the 2nd one. Just fixed that now. Thanks
