### ISSUE TITLE
Function predict in Gp.jl seems to be slow for default case (full_cov = false)

### ISSUE THREAD

**Issue by zerocewl** [STOR-i/GaussianProcesses.jl#22]
hello,

i tried some performance tests for the predict funtion in Gp.jl. For my testdata the default case was 3x-5x slower then the full cov case.
Maybe someone can replace the original upper version with the faster one in the lower code example.
Additional i will suggest to add some performance tests, to ensure that coming changes will not decrease the performance.
(Note: as always for performance tests julia needs some 'warmup' calls before timing stays stable.)

Original "slow" version:

```
function predict(gp::GP, x::Matrix{Float64}; full_cov::Bool=false)
    size(x,1) == gp.dim || throw(ArgumentError("Gaussian Process object and input observations do not have consistent dimensions"))
    if full_cov
        return _predict(gp, x)
    else
        ## calculate prediction for each point independently
            mu = Array(Float64, size(x,2))
            Sigma = similar(mu)
        for k in 1:size(x,2)
            out = _predict(gp, x[:,k:k])
            mu[k] = out[1][1]
            Sigma[k] = out[2][1]
        end
        return mu, Sigma
    end
end
```

Faster one:

```
function predict(gp::GP, x::Matrix{Float64}; full_cov::Bool=false)
    size(x,1) == gp.dim || throw(ArgumentError("Gaussian Process object and input observations do not have consistent dimensions"))
    mu, Sigma = _predict(gp, x);
    if ~full_cov # use reduced predictive covariance
      Sigma = diag(Sigma);
    end
    return mu, Sigma
end
```

Please correct me if some informations are lost in my suggestion.

**Comment by nemethis** [comment]
When I ran the comparison the current implementation was faster. What was the test you did?
In any case, I think there's probably a faster way of doing this using diagonal matrices.

We have some performance tests in the "perf" folder which we're working to expand.
