### ISSUE TITLE
Sign of derivative of log likelihood with respect to mean parameters seems to have the wrong sign

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#26]
The gradient of the log likelihood with respect to the mean parameter doesn't match its numerical approximation. In fact it seems to be the right number but the wrong sign. The gradient is computed in `GP.jl` as `gp.dmLL[i+noise] = -dot(Mgrads[:,i],gp.alpha)`. I'm not sure how that's obtained, so I don't know if that minus sign should just be removed, or if the issue runs deeper.

```{julia}
using GaussianProcesses

# Simulate example
n = 10
x = 2π * rand(n)
μ = 0.2
y = μ + sin(x) + 0.05*randn(n)
mConst = MeanConst(0.0) # constant mean
kern = SE(0.0,0.0)
logObsVar = -1.0
gp = GP(x,y,mConst,kern, logObsVar)      # Fit the GP

GaussianProcesses.update_mll_and_dmll!(gp)
prev_mLL=gp.mLL
prev_dmLL=gp.dmLL
prev_params=GaussianProcesses.get_params(gp)

dθ=[0.0, 1.0, 0.0, 0.0]*1e-4 # increment mean parameter
GaussianProcesses.set_params!(gp, prev_params.+dθ)
GaussianProcesses.update_mll_and_dmll!(gp)

println("change in log likelihood: ", gp.mLL-prev_mLL)
println("expected change in log likelihood: ", dot(prev_dmLL, dθ))
```

> change in log likelihood: 4.723900128666969e-5
expected change in log likelihood: -4.7253655770280115e-5

No problem for the other parameters:
```{julia}
prev_mLL=gp.mLL
prev_dmLL=gp.dmLL

prev_params=GaussianProcesses.get_params(gp)

dθ=[1.0, 0.0, 1.0, 1.0]*1e-4 # increment all other parameters
GaussianProcesses.set_params!(gp, prev_params.+dθ)
GaussianProcesses.update_mll_and_dmll!(gp)

println("change in log likelihood: ", gp.mLL-prev_mLL)
println("expected change in log likelihood: ", dot(prev_dmLL, dθ))
```

> change in log likelihood: -0.0007003607397644274
expected change in log likelihood: -0.0007003395285220553

**Comment by nemethis** [comment]
Sorry for the slow reply I've been away for the past few weeks.

Thanks for noticing this, surprised that we missed it. You are right that the `gp.dmLL[i+noise]` should equal `dot(Mgrads[:,i],gp.alpha)`. The minus was a result of the way we originally implemented the log-likelihood, where we initially had it set as the negative log-likelihood for the optimizer. This has now been changed so the optimizer minimizes `-gp.mLL`. Looks like we missed a minus sign when we changed things over. I've now fixed and pushed this change.

Importantly, the log-likelihood is correct so the optimizer should still correctly maximise this function, albeit less efficiently with an incorrect gradient. You should now find that the optimizer will require fewer gradient evaluations for convergence.

We're working at further developing the unit tests to hopefully catch these sorts of errors. Quite a few of these have already been implemented to check the kernels and we're now looking at comparing the hard coded derivatives against their automatic derivative counterparts.

**Comment by maximerischard** [comment]
Thank you for fixing the issue! The optimizer was actually failing to converge because it was getting confused by the gradient pointing in the wrong direction, so this is a big improvement.

**Comment by nemethis** [comment]
Great! I'm working on adding in some MCMC routines as an alternative to the optimizer function (see branch). The MALA and HMC algorithms, which rely on gradient calculations, should also benefit a lot from this fix.
