### ISSUE TITLE
Possible to merge noise branch into master?

### ISSUE THREAD

**Issue by rcthomas** [STOR-i/GaussianProcesses.jl#28]
I'm wondering if the functionality in the noise branch (possibly extended to handle a full error covariance matrix) is slated to be merged into master?

**Comment by nemethis** [comment]
Good question. We originally created this branch as a special request for someone working on a particular project, but we let it get stale as we weren't sure if it would more widely beneficial to others. 

I'll have a think about how best to merge this into master. In the meantime I've merged the master branch into the noise branch so it's at least using the most up to date functionality of the rest of the package.

**Comment by fairbrot** [comment]
I think observation noise (whether with diagonal or full covariance matrix) would be best handled through a new kernel. I'm not sure it would make sense in this case to optimize the parameters, in which case this kernel would have no adjustable parameters.

We'll have a go at implementing this if I have time, but please feel free to implement this yourself and make a pull request.

**Comment by rcthomas** [comment]
Thanks, I've been able to do my test problem with master merged into noise.  I do agree that this could be implemented through a new kernel with no adjustable parameters.

**Comment by maximerischard** [comment]
See issue #70.
