### ISSUE TITLE
simple bug: no parameter \ell in Mat52Ard

### ISSUE THREAD

**Issue by stefantj** [STOR-i/GaussianProcesses.jl#32]
Really too simple to justify a PR. Line 21 of mat52_ard.jl should be: 

21     mat.ℓ2 = exp(hyp[1:(mat.dim-1)])

rather than 

21     mat.ℓ = exp(hyp[1:(mat.dim-1)])

**Comment by fairbrot** [comment]
Have now fixed this. Thanks!
