### ISSUE TITLE
Ability to fix specified parameters in mean functions and kernels

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/GaussianProcesses.jl#33]

**Comment by maximerischard** [comment]
Two options spring to mind:
1. A wrapper kernel along the lines of the `Masked` kernel, that just modifies the get_params, set_params, and derivative functions to target a subset of the parameters.
2. Replace each parameter in each kernel with a new Parameter type, that has a `value::Float64` and a `fixed::Bool` attribute. This is what GPy does.

I'm inclined to start with the first option, and see what that looks like. I think adding complexity to every single kernel implementation won't be as pleasing.

**Comment by maximerischard** [comment]
The first option is now implemented on branch [fixed_parameters](https://github.com/STOR-i/GaussianProcesses.jl/compare/fixed_parameters). The idea is very simple (just hide one of the parameters), but the implementation is made quite ugly by having to write a line of boilerplate for each function to gets passed to the wrapped kernel. Ideas to make the code cleaner are welcomed.

**Comment by maximerischard** [comment]
What's the best way forward? Should I create a pull request?

**Comment by nemethis** [comment]
Sorry for the slow reply. If you give me a couple of days I can have a closer look and see if I have any additional thoughts. No need to do a pull request, once we're happy with the changes you can simply merge the branch.

**Comment by fairbrot** [comment]
This looks fine for now. We can't think of a cleaner way of delegating the cov methods at the moment.

Did you delete the FixedPeriodic kernel? I notice we're still exporting it in the module script but can't find its definition. If we still had it, it would be interesting to compare its performance with the wrapper kernel (I'm guessing it'd be just as efficient).

You can merge this into the master if you like, but it may be worth revisiting the second option later on if we need a parameter type for implementing priors.

I think we should all use pull requests for merging branches like this as they make it easier to view and comment on the changes.

**Comment by maximerischard** [comment]
Sure, good idea, here's an example:

```{julia}
using GaussianProcesses
per = Periodic(-1.0, -1.0, 0.0)
fper = FixedPeriodic(-1.0, -1.0, 0.0)
perfix = fix(per, :lp)

```
