### ISSUE TITLE
Auto-differentiation for user defined kernels

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/GaussianProcesses.jl#38]
The idea is to allow users to easily create new kernels with defined gradients by just specifying a covariance function. ForwardDiff might be used for this.

**Comment by maximerischard** [comment]
Hi Jamie,
One of my motivations for the changes I've been working on in the `faster_sum` branch is to enable kernel auto-differentiation. Have a look at the (new) `dmll_kern!` function:
```julia
function dmll_kern!(dmll::VecF64, k::Kernel, X::MatF64, data::KernelData, ααinvcKI::MatF64)
    dim = size(X, 1)
    nparams = num_params(k)
    @assert nparams == length(dmll)
    nobsv = size(X, 2)
    dmll[:] = 0.0
    @inbounds for j in 1:nobsv
        # off-diagonal
        for i in 1:j-1
            for iparam in 1:nparams
                dKij = dKij_dθp(k,X,data,i,j,iparam,dim)
                dmll[iparam] += dKij * ααinvcKI[i, j]
            end
        end
        # diagonal
        for iparam in 1:nparams
            dKjj = dKij_dθp(k,X,data,j,j,iparam,dim)
            dmll[iparam] += (dKjj * ααinvcKI[j, j]) / 2.0
        end
    end
    return dmll
end
```
You'll notice that the inner loop is now over the parameters for a single i,j pair of observations. That means if you can obtain a gradient vector via forward autodiff just before the `for iparam in 1:nparams` loops start, and replace the `dKij_dθp` calls by accessing this gradient, it should be possible to make it work.

**Comment by maximerischard** [comment]
I've taken a few steps towards supporting autodifferentiation on the `autodiff` branch. There's an `autodiff` function that turns a normal kernel into an autodiff kernel. So far it only works for simple isotropic kernels:

```julia
using GaussianProcesses
function prep(kern)
    d = 10
    nt = 1000
    Random.seed!(1)
    X = Random.randn(d, nt) # Training data
    Y = Random.randn(nt)
    gp = GP(X, Y, MeanConst(0.0), kern, log(1.0))
    return gp
end
rq = RQIso(0.0, 0.0, 0.0)
rq_ad = autodiff(rq)

gp_rq = prep(rq)
gp_ad = prep(rq_ad)

buf = Array{Float64}(undef, gp_rq.nobs, gp_rq.nobs)
GaussianProcesses.update_mll_and_dmll!(gp_rq, buf)
normal_dmll = gp_rq.dmll

GaussianProcesses.update_mll_and_dmll!(gp_ad, buf)
autodiff_dmll = gp_ad.dmll
@assert autodiff_dmll ≈ normal_dmll
```

And it's a bit slow:
```julia
GaussianProcesses.update_mll_and_dmll!(gp_rq, buf)
GaussianProcesses.update_mll_and_dmll!(gp_ad, buf)

@time GaussianProcesses.update_mll_and_dmll!(gp_rq, buf)
@time GaussianProcesses.update_mll_and_dmll!(gp_ad, buf)
```
```
0.099821 seconds (1.02 k allocations: 134.047 KiB)
0.315973 seconds (1.50 M allocations: 160.508 MiB, 4.23% gc time)
```

So, very much a work in progress, but this is a starting point.

**Comment by maximerischard** [comment]
With the latest commit on the autodiff branch, the speed difference is now gone for `RQIso`:
```
  0.100348 seconds (1.02 k allocations: 134.047 KiB)
  0.101063 seconds (1.02 k allocations: 134.047 KiB)
```
The main challenge is in constructing the `AutoDiffKernel` in the first place. For kernel objects with parameters of type `Float64`, I need a copy that has parameters of types `Forward.Dual`. And this needs to happen recursively for wrapped and composite kernels. I'm not sure how to do this…
