### ISSUE TITLE
Base computations on PDmats.jl 

### ISSUE THREAD

**Issue by scheidan** [STOR-i/GaussianProcesses.jl#4]
Great package! Especially the having the gradient ready for optim is very neat.

It may be a good idea to base the computations on the [PDMats](https://github.com/JuliaStats/PDMats.jl) package. This would 
1. outsource problems of numerical correct implementation (although I think you did a good job here),
2. make use of sparsity of covariance matrices for kernels with compact support.

The later point was actually my motivation to include a sparse matrices in PDMats.

PS: Also [MLKernels](https://github.com/trthatcher/MLKernels.jl) might be interesting to look at.

**Comment by fairbrot** [comment]
Thanks for the feedback. This is a good idea, we will look into this.

**Comment by fairbrot** [comment]
PDMats is now used for PD matrix calculations. This simplifies the code in places and significantly improves the speed of the update (and consequently the optimize!) functions. Thanks again for the suggestion.
