### ISSUE TITLE
Features vs GPy

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [STOR-i/GaussianProcesses.jl#42]
How does GaussianProcesses.jl compare - feature-wise - with GPy?
Is it production-ready?
Thanks!

**Comment by nemethis** [comment]
Currently, GPy is more developed than GaussianProcesses.jl. In particular, GPy can handle non-Gaussian likelihoods, which are useful for classification type problems. We're currently in the process of extending the functionality of GaussianProcesses.jl and hopefully by Christmas, we should have the main features of GPy implemented. 

In terms of regression, I think we have about the same functionality as GPy, so there's not much difference here. However, some preliminary tests show that GaussianProcesses.jl is faster than GPy #37 and this is something that we're consciously trying to improve upon.

**Comment by alessandrousseglioviretta** [comment]
Very good, thanks!
