### ISSUE TITLE
Kernels operating in different domains

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [STOR-i/GaussianProcesses.jl#45]
Is it possible to have kernels operate in different domains, as described in the GPy documentation "[basic kernels, operating on different domains](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_kernels.ipynb#Operating-on-different-domains)"?

Thanks!

**Comment by maximerischard** [comment]
Yes, this is exactly what [Masked](https://github.com/STOR-i/GaussianProcesses.jl/pull/36) kernels are intended for. This is a pretty recent feature, so the API is a little rough around the edges (and undocumented). Let us know if you have any suggestions for making it more intuitive.

**Comment by alessandrousseglioviretta** [comment]
Great, thanks!
