### ISSUE TITLE
Breaking changes in Optim v0.8

### ISSUE THREAD

**Issue by anriseth** [STOR-i/GaussianProcesses.jl#46]
I see you are using Optim with this package. As a heads-up, there will be some breaking changes in Optim v0.8: https://github.com/JuliaOpt/Optim.jl/pull/337 https://github.com/JuliaOpt/Optim.jl/issues/329

Tagging v0.8 is still some time away, but you may want to put an upper limit in REQUIRE to make sure things don't brake down the line.

**Comment by nemethis** [comment]
Thanks for letting us know.

**Comment by anriseth** [comment]
Optim 1.0 is also including some big breaking changes. The order of parameters in gradients and hessians are now following the "Julian" way of doing things. https://github.com/JuliaNLSolvers/Optim.jl/pull/392

**Comment by pkofod** [comment]
(do note that that change will be softly deprecated, so you will simply receive a warning if you use the old style)
