### ISSUE TITLE
Can't make plot() work in Julia 0.5

### ISSUE THREAD

**Issue by ko56** [STOR-i/GaussianProcesses.jl#47]
I am using the linear_trend.jl example:

using GaussianProcesses
using PyPlot

x=[-4.0,-3.0,-1.0,0.0,2.0];
y = 2.0*x + 0.5*rand(5);
xpred = collect(-5.0:0.1:5.0);
mLin = MeanLin([0.5])  # linear mean function
kern = SE(0.0,0.0)     # squared exponential kernel function
gp = GP(x,y,mLin,kern) # fit the GP
# This is supposed to use the function 'PyPlot.plot()' defined in src/glue/PyPlot.jl,
# but it doesn't:
# plot(gp)

This works, and the gp object is correctly returned.   But when I do 'plot(gp)', I get a long error:

ERROR: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('float() argument must be a string or a number',)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3161, in plot
    ret = ax.plot(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1383, in plot
    self.add_line(line)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1703, in add_line
    self._update_line_limits(line)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1725, in _update_line_limits
    path = line.get_path()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/lines.py", line 938, in get_path
    self.recache()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/lines.py", line 634, in recache
    y = np.asarray(yconv, np.float_)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)

 in pyerr_check at /usr/home/ko/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /usr/home/ko/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /usr/home/ko/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyCall/src/PyCall.jl:550
 in _pycall(::PyCall.PyObject, ::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyCall/src/PyCall.jl:538
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyCall/src/PyCall.jl:572
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyCall/src/PyCall.jl:572
 in #plot#85(::Array{Any,1}, ::Function, ::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyPlot/src/PyPlot.jl:172
 in plot(::GaussianProcesses.GP, ::Vararg{GaussianProcesses.GP,N}) at /usr/home/ko/.julia/v0.5/PyPlot/src/PyPlot.jl:169
 in _init at /usr/local/lib/julia/sys.so:? (repeats 2 times)
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68

julia>

**Comment by fairbrot** [comment]
Because of the way we have set up PyPlot functionality, you need to import PyPlot before GaussianProcesses or run the function `GaussianProcesses.PyPlot_init()`.

This isn't ideal, but in the near future we will use the Plots.jl package for plotting. See #48.

**Comment by ko56** [comment]
Very good, thanks.  I was also going to suggest using Plots ...
