### ISSUE TITLE
Use Plots.jl for plotting

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/GaussianProcesses.jl#48]
Using the Plots.jl package would remove the need to define optional package dependencies and define plotting functions for each plotting back end. This would open up many new plotting back-ends (such as Plotly) and only the skeleton package RecipesBase.jl would need to be added to REQUIRE.

**Comment by kskyten** [comment]
This seems to be implemented in the `plot` branch. Can it be merged? I have a recipe for 2D GPs.

**Comment by fairbrot** [comment]
Could you make a pull request on the plotting branch? Once this is added to the plot branch, I'll delete the old plotting functions in master and merge.
