### ISSUE TITLE
Using keyword arguments in optimize!

### ISSUE THREAD

**Issue by SamuelWiqvist** [STOR-i/GaussianProcesses.jl#50]
Hi all,

I have a problem with passing keyword arguments from optimize! to the function optimize of the Optim.jl package. 

When I try to set the number of iterations for the optimization (i.e. setting the keyword argument _iterations_) I get:
 
![kwarg_problem](https://cloud.githubusercontent.com/assets/12857904/23669437/7292b78e-0364-11e7-91aa-b557811d2cc3.PNG)

What is the proper way to use keyword arguments in optimize!?

Information about my system: 
![juliaversioninfo](https://cloud.githubusercontent.com/assets/12857904/23669927/425e7e8e-0366-11e7-86e9-1438a7d8d8c0.PNG)

Version of GaussianProcesses.jl:
![gpversion](https://cloud.githubusercontent.com/assets/12857904/23669900/21d396ae-0366-11e7-8949-b261b47028e5.PNG)

**Comment by maximerischard** [comment]
Ah yes, I've bumped into this. The Optim syntax changed a little bit. What seems to be needed now is:
```julia
optimize(func,init,method, Optim.Options(;kwargs...))
```
instead of
```julia
optimize(func,init; method=method, kwargs...)
```
Would you be interested in putting together a pull request? The source file that needs to be updated is `src/optimize.jl`

**Comment by SamuelWiqvist** [comment]
Thanks for the fast answer! 

It didn't work to change the syntax to the Optim syntax. However I instead changed the optimize! function to use a Optim.Options object instead of storing the optimization settings in kwargs.  I now have following code om my local computer: 

```julia
@doc """
# Description
A function for optimising the GP hyperparameters based on type II maximum likelihood estimation. This function performs gradient based optimisation using the Optim pacakge to which the user is referred to for further details.

# Arguments:
* `gp::GP`: Predefined Gaussian process type
* `noise::Bool`: Noise hyperparameters should be optmized
* `mean::Bool`: Mean function hyperparameters should be optmized
* `kern::Bool`: Kernel function hyperparameters should be optmized
* `options`: Optim.Options object containing the keyword arguments for the optimize function from the Optim package

# Return:
* `::Optim.MultivariateOptimizationResults{Float64,1}`: optimization results object
""" ->
function optimize!(gp::GP; noise::Bool=true, mean::Bool=true, kern::Bool=true,
                    method=ConjugateGradient(), options::Optim.Options{Void} = Optim.Options())
    func = get_optim_target(gp, noise=noise, mean=mean, kern=kern)
    init = get_params(gp;  noise=noise, mean=mean, kern=kern) # Initial hyperparameter values
    results=optimize(func,init, method, options) # Run optimizer
    set_params!(gp, Optim.minimizer(results), noise=noise,mean=mean,kern=kern)
    update_mll!(gp)
    return results
end
```

And if I now run 

```julia
res = optimize!(gp, options = Optim.Options(iterations = 10))`
```

I get

![res](https://cloud.githubusercontent.com/assets/12857904/23676775/1249ccea-037e-11e7-8788-91196ddbc093.PNG)

I will put together a pull request during the next few days.

**Comment by chris-nemeth** [comment]
Thanks for this. I've merged the PR.
