### ISSUE TITLE
Support for multiple regression (beyond 2-dim)

### ISSUE THREAD

**Issue by arturgower** [STOR-i/GaussianProcesses.jl#54]
Great package. At the moment only 2-dim regression for `X = 2×n Array{Float64,2}` is supported right? Do you guys have any plans to extend this to higher dimensions?

**Comment by maximerischard** [comment]
The package supports more than 2 dimensions. Furthermore, the [Masked kernel](https://github.com/STOR-i/GaussianProcesses.jl/pull/36) allows you to specify that a kernel only operates in a subset of the dimensions of X. The only limitation along those lines is that we only support one-dimensional outputs (Y is a vector).
