### ISSUE TITLE
Introducing GeoStats.jl

### ISSUE THREAD

**Issue by juliohm** [STOR-i/GaussianProcesses.jl#55]
I am happy to introduce [GeoStats.jl](https://github.com/juliohm/GeoStats.jl), a package that contains generalizations of Gaussian processes to situations where the mean of the random field is unknown and where more general covariance metrics are needed. It includes Gaussian processes as a special case and supports many other features for geostatistical analysis.

GeoStats.jl has a lot of overlap with GaussianProcesses.jl at the implementation level, and some of you might find it useful in your work. I opened this issue to share the project with you.

I am planning to unify many other geostatistical methods in future releases, please feel free to watch the project or mention it in the README if you think it can be useful to other people in the community.

I have written a few examples to illustrate the current features:

http://nbviewer.jupyter.org/github/juliohm/GeoStats.jl/tree/master/examples/

**Comment by chris-nemeth** [comment]
Hi Julio,

Thanks for letting us know about GeoStats.jl, it looks like a great package. We're glad to see that you've started developing a geostatistics package for the Julia language. 

We're in the process of updating GaussianProcesses.jl significantly to allow for non-Gaussian likelihoods. Hopefully we'll be merging these changes into the master branch in a day or so. I'll also add a link to your package on our README file.

Chris

**Comment by juliohm** [comment]
Thank you Chris, it is good to hear about new features coming up in GaussianProcesses.jl. Also, I appreciate the mention in the README. One of my goals with GeoStats.jl is to educate people about the existence of geostatistics and the generalizations therein.

**Comment by maximerischard** [comment]
Hi Julio,
It's great to see work on the geostatistics front. A lot of my applied projects at the moment are also related to geostats, which is what got me interested in this package in the first place. Did you consider importing `GaussianProcesses.jl` for kriging? It's a bit of a shame to duplicate those efforts, and I'd be curious to hear what functionality you needed and couldn't find.

**Comment by juliohm** [comment]
Hi Maxime,

Thank you, I am happy to see Geostatistics in the real world, and one of my
goals with the package is to educate people about its existence.

Gaussian processes and Simple Kriging are essentially two names for the
same concept and we have other more general interpolation methods that are
more practical in our field. Given the number of features that GeoStats.jl
supports and will support, it wouldn't be practical to merge the projects,
there is still lots to come.

For example, we sometimes need spatial structure that is non stationary ,
and we cannot restrict ourselves to stationary covariance kernels like in
normal Gaussian processes.

I'm happy to discuss more about it, I'm currently on vacation, but will be
back after 2 weeks.

Best,
