### ISSUE TITLE
Use RDatasets in classification notebook

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/GaussianProcesses.jl#62]
The data in the notebook directory is available through the RDatasets package:

```julia
using RDatasets

crab_data = datasets("MASS", "crabs")
```

Using RDatasets will eliminate the need to store the data files currently being used. It may also serve as a good example of how to construct a GP object from a DataFrame.

**Comment by chris-nemeth** [comment]
Agreed. I'll do this tonight.

**Comment by chris-nemeth** [comment]
Done. However, I noticed that the notebooks are rather large. Need to find a way of either making them smaller, or moving them out of the package.

**Comment by maximerischard** [comment]
It looks like you've got SVG plots in there that are taking up a lot of room. In my experience, SVG makes a lot of sense in theory, but doesn't work well in a lot of browsers, and tend to make notebooks really slow for complex plots. I've mostly switched to high-resolution PNG plots for my work, which has made life easier.

**Comment by chris-nemeth** [comment]
Good suggestion. Once Jamie has finished work on the [Plot.jl](https://github.com/JuliaPlots/Plots.jl) interface we'll be able to use a wider range of plotting packages.

**Comment by chris-nemeth** [comment]
Switched notebook plots to PNG
