### ISSUE TITLE
Syntax changes for julia v0.6

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#64]
I'm going to start a new branch for updating the syntax for julia v0.6. I'm going to assume we're not bothered with retaining v0.5 syntax compatibility, as that's a lot more work. Is that ok?

**Comment by chris-nemeth** [comment]
Fine with me. I don't think we should worry about preserving backwards compatibility until Julia hits v1.0.

**Comment by fairbrot** [comment]
Again, my preference would be to try to maintain compatibility with the previous version of Julia (v0.5 in this case) if possible, as do many other popular packages such as Distributions.jl, JuMP.jl etc. Many people will be slow to update their version of Julia. This may especially true for users of Ubuntu (me and Chris included) as I notice there are no longer platform-specific installation instructions for this on the official Julia website. 

The Compat package.jl exists for this purpose and I am happy to help with this task. If it really is too difficult we can drop support, but it is definitely worth trying.

**Comment by chris-nemeth** [comment]
I haven't updated to v0.6 yet, are there any breaking changes that will affect the package?

**Comment by fairbrot** [comment]
As far as I can tell the package is still working (the unit tests run without error), but there are a lot of deprecation warnings. Some like:

```julia
WARNING: deprecated syntax "abstract KernelData" at /home/fairbrot/.julia/v0.6/GaussianProcesses/src/kernels/kernels.jl:15.
Use "abstract type KernelData end" instead.
```

will be easy to fix with Compat.jl:

```julia
@compat abstract type VariateForm end
```

**Comment by maximerischard** [comment]
It all works, with one exception. If `x` is a Vector of length `n`, then `x'` is no longer a 1 x n matrix, but is now a `RowVector`, and so the `GPE` constructor fails for vectors.

**Comment by chris-nemeth** [comment]
For now, we could convert the vectors to arrays, but it would be nicer if we could find a more elegant solution rather using this transpose trick.

**Comment by fairbrot** [comment]
I'm guessing RowVector works like a 1 x n matrix so another possibility would be edit our functions and types so that X can be a row vector as well as a matrix.

**Comment by maximerischard** [comment]
Yes, both approaches work. X would be an `AbstractMatrix{Float64}` instead of `Matrix{Float64}`.

**Comment by chris-nemeth** [comment]
Changed to `AbstractMatrix{Float64}`

**Comment by chris-nemeth** [comment]
I think all these issues have now been dealt with.
