### ISSUE TITLE
Update METADATA.jl for Version 0.5.0?

### ISSUE THREAD

**Issue by jarvist** [STOR-i/GaussianProcesses.jl#72]
Currently 0.4 is installed by Julia; I assume because the central METADATA has not been updated?

The hard requirement of < Optim 0.8 makes it quite painful to use the master of this package, alongside my other codes. Is there that much effort to get it working? 

I tried to see what breaks on a local copy, but ended up in a tangle of REQUIREments!

**Comment by jarvist** [comment]
Ah, I see - METADATA has been updated!
But upgrading to 0.5 requires Klara, which in turn leads to a massive number of regressions, due to it's REQUIRE pins to old versions of ForwardDiff & etc. So the Julia package manager was hanging on 0.4 for me.

**Comment by chris-nemeth** [comment]
Thanks for bringing this up. The [Optim](https://github.com/JuliaNLSolvers/Optim.jl) people warned us about breaking changes after v0.8 which is why we truncated the requirement. I'll have a closer look at all of the requirements as we may be able to update a few of them now.

**Comment by jarvist** [comment]
Mostly it is a re-ordering of the arguments (to make them more canonically Julian), and DifferentiableFunction() --> OnceDifferentiable() etc. 
I have a local Master copy of GaussianProcesses, with Klara removed, which is failing quite abysmally in its tests against Optim 0.10.1 , but the code does at least attempt to run.

**Comment by maximerischard** [comment]
It's definitely an issue that the Klara dependency is leading to regressions. I've removed the Klara import on my local install for that reason. Updating to a newer version of Optim would be fairly easy otherwise. Our options seem to be:
1. wait for Klara to update their requirements
2. reimplement HMC and remove the Klara requirement
3. use another package for HMC, for example Mamba or Turing

None of these options is very appealing, so I'm not sure what we should do.

**Comment by chris-nemeth** [comment]
I'll have a look at the Optim branch. I think it's time to resolve this now given that Optim is at v0.10.0.

I thought the Klara issues were resolved. When Klara was broken under Julia v0.6 I implemented our own HMC sampler as a temporary fix. We could easily reintroduce this if we wanted to remove the Klara dependency. Utilising other packages is also an option and would offer users a greater variety of samplers to choose from when doing MCMC. I think we just need to make a decision on this for going forward.

**Comment by maximerischard** [comment]
The problem is that Klara [requires](https://github.com/JuliaStats/Klara.jl/blob/master/REQUIRE) older versions of ForwardDiff and ReverseDiff, which itself causes regressions.

**Comment by jarvist** [comment]
Indeed. Klara's REQUIRE is quite a painful set of package pinnings. It's no wonder retrospectively that Julia was refusing to move to a Klara-using version of GaussianProcesses. Does anyone have any interaction with the Klara team, and are they planning to update / soften the requirements soon?

**Comment by chris-nemeth** [comment]
I know the main Klara developer. I can ask Theo @scidom, why does Klara have a cap on these dependencies and whether they can be removed?

**Comment by scidom** [comment]
I will check if we can remove the cap on the autodiff dependencies. They are there because the latest autodiff upgrade was initially buggy. Let me check if the bugs have now been fixed, in which case I can upgrade Klara accordingly.

**Comment by chris-nemeth** [comment]
Thanks Theo.

**Comment by jarvist** [comment]
Hi everybody,
It looks like the REQUIRE file (now on Julia 0.6) is all hunky dory, with no need to pin packages. Happy to close this issue?

**Comment by chris-nemeth** [comment]
Yes.
