### ISSUE TITLE
Type instabilities in MCMC branch

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#74]
There are a lot of type instabilities in `update_target_and_dtarget!` in `GPMC.jl`. With MCMC we evaluate the target many times, so these inefficiencies can add up, though it's hard to tell how much faster a type-stable version would be.

There are a few culprits:
* the priors can be of any type, and the kernels are not parametric
* `GPMC.lik::Likelihood` can hide a lot of types
* `GPMC.cK` is AbstractPDMat rather than just `PDMat` and `GPMC` is not parametric

**Comment by chris-nemeth** [comment]
Is this still an issue?
