### ISSUE TITLE
time for a new version

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#75]
There's been a lot of progress since 0.5.0. Could we make a new version and update METADATA?

**Comment by fairbrot** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/13614

**Comment by chris-nemeth** [comment]
I've made a couple extra changes (including adding Distributions to the REQUIRE). @fairbrot you can update and close this issue when you're ready.

**Comment by fairbrot** [comment]
New v0.6 pull request created: https://github.com/JuliaLang/METADATA.jl/pull/14290

**Comment by maximerischard** [comment]
Can we close this?

**Comment by chris-nemeth** [comment]
Yes
