### ISSUE TITLE
Slow gradient in MCMC

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#76]
I'm refactoring the likelihood gradient in GPMC. Test results below. I'm about to commit those changes.

```julia
#Load the package
using GaussianProcesses
using BenchmarkTools

#Simulate the data
srand(203617)
n = 500
X = collect(linspace(-3,3,n));
f = 2*cos.(2*X);
Y = [rand(Distributions.Poisson(exp.(f[i]))) for i in 1:n];
```

```julia
#GP set-up
k = Matern(3/2,0.0,0.0)   # Matern 3/2 kernel
l = PoisLik()             # Poisson likelihood
gp = GP(X, vec(Y), MeanZero(), k, l)
;
```

```julia
module MCMC2
    using GaussianProcesses
    import GaussianProcesses: dlog_dens_df
    using PDMats
    
    function dll_f(gp::GPMC)
        Lv = unwhiten(gp.cK,gp.v)
        dl_df=dlog_dens_df(gp.lik, Lv + gp.μ, gp.y)
        U = triu(gp.cK.chol.factors)
        L = U'
        return L'dl_df
    end
    
    function dll_f2(gp::GPMC)
        Lv = unwhiten(gp.cK,gp.v)
        dl_df=dlog_dens_df(gp.lik, Lv + gp.μ, gp.y)
        U = triu(gp.cK.chol.factors)
        return U*dl_df
    end
    
    function dll_f3(gp::GPMC)
        Lv = unwhiten(gp.cK, gp.v)
        dl_df = dlog_dens_df(gp.lik, Lv + gp.μ, gp.y)
        A_mul_B!(gp.cK.chol[:UL], dl_df)
        return dl_df
    end
end
```

    MCMC2

```julia
dll_f_out = MCMC2.dll_f(gp)
@benchmark MCMC2.dll_f(gp)
```

    BenchmarkTools.Trial: 
      memory estimate:  3.83 MiB
      allocs estimate:  11
      --------------
      minimum time:     1.046 ms (0.00% GC)
      median time:      1.643 ms (0.00% GC)
      mean time:        1.708 ms (12.60% GC)
      maximum time:     5.513 ms (36.85% GC)
      --------------
      samples:          2909
      evals/sample:     1

```julia
dll_f2_out = MCMC2.dll_f2(gp)
@benchmark MCMC2.dll_f2(gp)
```

    BenchmarkTools.Trial: 
      memory estimate:  1.93 MiB
      allocs estimate:  9
      --------------
      minimum time:     468.281 μs (0.00% GC)
      median time:      789.237 μs (0.00% GC)
      mean time:        931.242 μs (14.04% GC)
      maximum time:     3.923 ms (52.53% GC)
      --------------
      samples:          5313
      evals/sample:     1

```julia
dll_f3_out = MCMC2.dll_f3(gp)
@benchmark MCMC2.dll_f3(gp)
```

    BenchmarkTools.Trial: 
      memory estimate:  16.34 KiB
      allocs estimate:  8
      --------------
      minimum time:     466.434 μs (0.00% GC)
      median time:      539.144 μs (0.00% GC)
      mean time:        648.976 μs (0.16% GC)
      maximum time:     3.033 ms (64.87% GC)
      --------------
      samples:          7644
      evals/sample:     1

```julia
maximum(abs.(dll_f2_out .- dll_f_out))
```

    4.973799150320701e-14

```julia
maximum(abs.(dll_f3_out .- dll_f_out))
```

    4.263256414560601e-14

**Comment by maximerischard** [comment]
I'm seeing a 3x speed-up. Chris, could you have a look at 63f8dcd3728ea630af636b5cd1d5a0eb0ec094c2 and check it all makes sense?

**Comment by chris-nemeth** [comment]
These are impressive speed-ups. I've checked the code and everything seems fine. The changes did cause problems for GPE which I've now fixed so I'll close this issue
