### ISSUE TITLE
Non constant observation noise

### ISSUE THREAD

**Issue by JonnyCBB** [STOR-i/GaussianProcesses.jl#8]
Hi 

Thank you for creating this package. I only found out about GPR a few months ago and I was hoping to implement it in an algorithm I hope to write soon.
Going through the Readme it looks as though you can only specify a single value for the (log) observation noise which I assume is applied to all observations equally.
In my case (I do research in X-ray crystallography) each observation is given it's own error. Is there support for specifying a Vector of (log) observation noise to correspond to each observation?

**Comment by nemethis** [comment]
Hi,

You're right that at the moment we don't support this. I've created a branch called "noise" which allows each observation to have it's own error. When using the optimize! function to estimate the parameters you'll need to set noise=true to estimate these parameters. I'm not sure how well this will work with so many noise parameters, you may end up overfitting the model.

Good luck!

**Comment by JonnyCBB** [comment]
Thanks for getting back to me. Really appreciate it. In my case the observation errors are given and hence I don't need to optimize these parameters. I've never implemented GPR so I could be wrong but my understanding from reading [this paper](http://www.robots.ox.ac.uk/~mebden/reports/GPtutorial.pdf) was that you could specify the observation noise for each observation and keep those as specified and only optimize the hyperparameters. Is this the case or have I interpreted the method incorrectly?

**Comment by nemethis** [comment]
It's great that the errors are known and don't need to be estimated. Using the "noise" branch, by default the optimize! function will estimate only the mean and kernel hyperparamters and leave the noise parameters untouched. See "regression_1d.jl" in the docs folder.

**Comment by JonnyCBB** [comment]
Fantastic. Thank you
